# Data paths
data:
  train_dir: "data/train/train"
  test_dir: "data/test/test"
  train_list: "data/train/train_list.txt"
  test_list: "data/test/test_list.txt"
  output_dir: "output"
  results_dir: "output/results"
  predictions_dir: "output/predictions"

# Model parameters
model:
  input_size: [426, 560]
  in_channels: 3
  out_channels: 1
  base_channels: 64

# Training parameters
training:
  batch_size: 4
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  num_epochs: 1
  train_val_split: 0.85
  num_workers: 4
  pin_memory: true
  device: "cuda"  # or "cpu"

# Data augmentation
augmentation:
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Evaluation
evaluation:
  metrics:
    - MAE
    - RMSE
    - siRMSE
    - REL
    - Delta1
    - Delta2
    - Delta3
  save_samples: 5  # Number of sample predictions to save 